sudo: false
notifications:
  email: false
language: python
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=coveralls
before_install:
  - "sed -i '/^cx-Oracle/s/^/#/' requirements.txt"
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
