MONGO_DBURI: 'mongodb://localhost:27017'
MONGO_DATABASE: 'oastats'
MONGO_COLLECTION: 'summary'

EMAIL_TEMPLATE: 'poast/message.tmpl'
EMAIL_SENDER: 'oastats@mit.edu'
EMAIL_SUBJECT: 'Download statistics for your articles in DSpace@MIT'
SMTP_HOST: 'localhost'

DOWNLOAD_THRESHOLD: 20

SQLALCHEMY_DB_URI: 'sqlite://'
