MONGO_DBURI: 'mongodb://localhost:27017'
MONGO_DATABASE: 'oastats'
MONGO_COLLECTION: 'summary'

EMAIL_TEMPLATE: 'poast/message.tmpl'
EMAIL_SENDER: 'oastats@mit.edu'

DOWNLOAD_THRESHOLD: 10

ORACLE_USER:  # <username>
ORACLE_PASSWORD:  # <password>
ORACLE_SID: DWRHS
ORACLE_HOST: warehouse.mit.edu
ORACLE_PORT: 1521
